//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.ChybaWsdlService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024chyba", ConfigurationName="ChybaWsdlService.Team024ChybaPortType")]
    public interface Team024ChybaPortType {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://labss2.fiit.stuba.sk/pis/students/team024chyba/types) of message getByIdRequest does not match the default value (http://labss2.fiit.stuba.sk/pis/students/team024chyba)
        [System.ServiceModel.OperationContractAttribute(Action="http://labss2.fiit.stuba.sk/pis/students/team024chyba/#getById", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebApi.ChybaWsdlService.getByIdResponse getById(WebApi.ChybaWsdlService.getByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://labss2.fiit.stuba.sk/pis/students/team024chyba/#getById", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApi.ChybaWsdlService.getByIdResponse> getByIdAsync(WebApi.ChybaWsdlService.getByIdRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://labss2.fiit.stuba.sk/pis/students/team024chyba/types) of message getByAttributeValueRequest does not match the default value (http://labss2.fiit.stuba.sk/pis/students/team024chyba)
        [System.ServiceModel.OperationContractAttribute(Action="http://labss2.fiit.stuba.sk/pis/students/team024chyba/#getByAttributeValue", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebApi.ChybaWsdlService.getByAttributeValueResponse getByAttributeValue(WebApi.ChybaWsdlService.getByAttributeValueRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://labss2.fiit.stuba.sk/pis/students/team024chyba/#getByAttributeValue", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApi.ChybaWsdlService.getByAttributeValueResponse> getByAttributeValueAsync(WebApi.ChybaWsdlService.getByAttributeValueRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://labss2.fiit.stuba.sk/pis/students/team024chyba/types) of message getByNumericConditionRequest does not match the default value (http://labss2.fiit.stuba.sk/pis/students/team024chyba)
        [System.ServiceModel.OperationContractAttribute(Action="http://labss2.fiit.stuba.sk/pis/students/team024chyba/#getByNumericCondition", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebApi.ChybaWsdlService.getByNumericConditionResponse getByNumericCondition(WebApi.ChybaWsdlService.getByNumericConditionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://labss2.fiit.stuba.sk/pis/students/team024chyba/#getByNumericCondition", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApi.ChybaWsdlService.getByNumericConditionResponse> getByNumericConditionAsync(WebApi.ChybaWsdlService.getByNumericConditionRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://labss2.fiit.stuba.sk/pis/students/team024chyba/types) of message getAllRequest does not match the default value (http://labss2.fiit.stuba.sk/pis/students/team024chyba)
        [System.ServiceModel.OperationContractAttribute(Action="http://labss2.fiit.stuba.sk/pis/students/team024chyba/#getAll", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebApi.ChybaWsdlService.getAllResponse getAll(WebApi.ChybaWsdlService.getAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://labss2.fiit.stuba.sk/pis/students/team024chyba/#getAll", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApi.ChybaWsdlService.getAllResponse> getAllAsync(WebApi.ChybaWsdlService.getAllRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://labss2.fiit.stuba.sk/pis/students/team024chyba/types) of message insertRequest does not match the default value (http://labss2.fiit.stuba.sk/pis/students/team024chyba)
        [System.ServiceModel.OperationContractAttribute(Action="http://labss2.fiit.stuba.sk/pis/students/team024chyba/#insert", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebApi.ChybaWsdlService.insertResponse insert(WebApi.ChybaWsdlService.insertRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://labss2.fiit.stuba.sk/pis/students/team024chyba/#insert", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApi.ChybaWsdlService.insertResponse> insertAsync(WebApi.ChybaWsdlService.insertRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://labss2.fiit.stuba.sk/pis/students/team024chyba/types) of message updateRequest does not match the default value (http://labss2.fiit.stuba.sk/pis/students/team024chyba)
        [System.ServiceModel.OperationContractAttribute(Action="http://labss2.fiit.stuba.sk/pis/students/team024chyba/#update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebApi.ChybaWsdlService.updateResponse update(WebApi.ChybaWsdlService.updateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://labss2.fiit.stuba.sk/pis/students/team024chyba/#update", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApi.ChybaWsdlService.updateResponse> updateAsync(WebApi.ChybaWsdlService.updateRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://labss2.fiit.stuba.sk/pis/students/team024chyba/types) of message deleteRequest does not match the default value (http://labss2.fiit.stuba.sk/pis/students/team024chyba)
        [System.ServiceModel.OperationContractAttribute(Action="http://labss2.fiit.stuba.sk/pis/students/team024chyba/#delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebApi.ChybaWsdlService.deleteResponse delete(WebApi.ChybaWsdlService.deleteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://labss2.fiit.stuba.sk/pis/students/team024chyba/#delete", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApi.ChybaWsdlService.deleteResponse> deleteAsync(WebApi.ChybaWsdlService.deleteRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024chyba/types")]
    public partial class Chyba : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string nameField;
        
        private int vytlacok_idField;
        
        private int pouzivatel_idField;
        
        private string staryUdajField;
        
        private string novyUdajField;
        
        private bool potvrdenaField;
        
        private int admin_idField;
        
        private System.DateTime datZalozeniaField;
        
        private System.DateTime datVyhodnoteniaField;
        
        private bool vyhodnotenaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int vytlacok_id {
            get {
                return this.vytlacok_idField;
            }
            set {
                this.vytlacok_idField = value;
                this.RaisePropertyChanged("vytlacok_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int pouzivatel_id {
            get {
                return this.pouzivatel_idField;
            }
            set {
                this.pouzivatel_idField = value;
                this.RaisePropertyChanged("pouzivatel_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string staryUdaj {
            get {
                return this.staryUdajField;
            }
            set {
                this.staryUdajField = value;
                this.RaisePropertyChanged("staryUdaj");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string novyUdaj {
            get {
                return this.novyUdajField;
            }
            set {
                this.novyUdajField = value;
                this.RaisePropertyChanged("novyUdaj");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public bool potvrdena {
            get {
                return this.potvrdenaField;
            }
            set {
                this.potvrdenaField = value;
                this.RaisePropertyChanged("potvrdena");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int admin_id {
            get {
                return this.admin_idField;
            }
            set {
                this.admin_idField = value;
                this.RaisePropertyChanged("admin_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public System.DateTime datZalozenia {
            get {
                return this.datZalozeniaField;
            }
            set {
                this.datZalozeniaField = value;
                this.RaisePropertyChanged("datZalozenia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public System.DateTime datVyhodnotenia {
            get {
                return this.datVyhodnoteniaField;
            }
            set {
                this.datVyhodnoteniaField = value;
                this.RaisePropertyChanged("datVyhodnotenia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public bool vyhodnotena {
            get {
                return this.vyhodnotenaField;
            }
            set {
                this.vyhodnotenaField = value;
                this.RaisePropertyChanged("vyhodnotena");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024chyba/types")]
    public partial class Chybas : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string nameField;
        
        private int vytlacok_idField;
        
        private int pouzivatel_idField;
        
        private string staryUdajField;
        
        private string novyUdajField;
        
        private bool potvrdenaField;
        
        private int admin_idField;
        
        private System.DateTime datZalozeniaField;
        
        private System.DateTime datVyhodnoteniaField;
        
        private bool vyhodnotenaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int vytlacok_id {
            get {
                return this.vytlacok_idField;
            }
            set {
                this.vytlacok_idField = value;
                this.RaisePropertyChanged("vytlacok_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int pouzivatel_id {
            get {
                return this.pouzivatel_idField;
            }
            set {
                this.pouzivatel_idField = value;
                this.RaisePropertyChanged("pouzivatel_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string staryUdaj {
            get {
                return this.staryUdajField;
            }
            set {
                this.staryUdajField = value;
                this.RaisePropertyChanged("staryUdaj");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string novyUdaj {
            get {
                return this.novyUdajField;
            }
            set {
                this.novyUdajField = value;
                this.RaisePropertyChanged("novyUdaj");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public bool potvrdena {
            get {
                return this.potvrdenaField;
            }
            set {
                this.potvrdenaField = value;
                this.RaisePropertyChanged("potvrdena");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int admin_id {
            get {
                return this.admin_idField;
            }
            set {
                this.admin_idField = value;
                this.RaisePropertyChanged("admin_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public System.DateTime datZalozenia {
            get {
                return this.datZalozeniaField;
            }
            set {
                this.datZalozeniaField = value;
                this.RaisePropertyChanged("datZalozenia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public System.DateTime datVyhodnotenia {
            get {
                return this.datVyhodnoteniaField;
            }
            set {
                this.datVyhodnoteniaField = value;
                this.RaisePropertyChanged("datVyhodnotenia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public bool vyhodnotena {
            get {
                return this.vyhodnotenaField;
            }
            set {
                this.vyhodnotenaField = value;
                this.RaisePropertyChanged("vyhodnotena");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getById", WrapperNamespace="http://labss2.fiit.stuba.sk/pis/students/team024chyba/types", IsWrapped=true)]
    public partial class getByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024chyba/types", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public getByIdRequest() {
        }
        
        public getByIdRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getByIdResponse", WrapperNamespace="http://labss2.fiit.stuba.sk/pis/students/team024chyba/types", IsWrapped=true)]
    public partial class getByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024chyba/types", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WebApi.ChybaWsdlService.Chyba chyba;
        
        public getByIdResponse() {
        }
        
        public getByIdResponse(WebApi.ChybaWsdlService.Chyba chyba) {
            this.chyba = chyba;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getByAttributeValue", WrapperNamespace="http://labss2.fiit.stuba.sk/pis/students/team024chyba/types", IsWrapped=true)]
    public partial class getByAttributeValueRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024chyba/types", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string attribute_name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024chyba/types", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string attribute_value;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024chyba/types", Order=2)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("id", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Nullable<int>[] ids;
        
        public getByAttributeValueRequest() {
        }
        
        public getByAttributeValueRequest(string attribute_name, string attribute_value, System.Nullable<int>[] ids) {
            this.attribute_name = attribute_name;
            this.attribute_value = attribute_value;
            this.ids = ids;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getByAttributeValueResponse", WrapperNamespace="http://labss2.fiit.stuba.sk/pis/students/team024chyba/types", IsWrapped=true)]
    public partial class getByAttributeValueResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024chyba/types", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("chyba", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WebApi.ChybaWsdlService.Chybas[] chybas;
        
        public getByAttributeValueResponse() {
        }
        
        public getByAttributeValueResponse(WebApi.ChybaWsdlService.Chybas[] chybas) {
            this.chybas = chybas;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getByNumericCondition", WrapperNamespace="http://labss2.fiit.stuba.sk/pis/students/team024chyba/types", IsWrapped=true)]
    public partial class getByNumericConditionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024chyba/types", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string attribute_name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024chyba/types", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string attribute_value;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024chyba/types", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string math_condition;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024chyba/types", Order=3)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("id", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Nullable<int>[] ids;
        
        public getByNumericConditionRequest() {
        }
        
        public getByNumericConditionRequest(string attribute_name, string attribute_value, string math_condition, System.Nullable<int>[] ids) {
            this.attribute_name = attribute_name;
            this.attribute_value = attribute_value;
            this.math_condition = math_condition;
            this.ids = ids;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getByNumericConditionResponse", WrapperNamespace="http://labss2.fiit.stuba.sk/pis/students/team024chyba/types", IsWrapped=true)]
    public partial class getByNumericConditionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024chyba/types", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("chyba", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WebApi.ChybaWsdlService.Chybas[] chybas;
        
        public getByNumericConditionResponse() {
        }
        
        public getByNumericConditionResponse(WebApi.ChybaWsdlService.Chybas[] chybas) {
            this.chybas = chybas;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAll", WrapperNamespace="http://labss2.fiit.stuba.sk/pis/students/team024chyba/types", IsWrapped=true)]
    public partial class getAllRequest {
        
        public getAllRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllResponse", WrapperNamespace="http://labss2.fiit.stuba.sk/pis/students/team024chyba/types", IsWrapped=true)]
    public partial class getAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024chyba/types", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("chyba", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WebApi.ChybaWsdlService.Chybas[] chybas;
        
        public getAllResponse() {
        }
        
        public getAllResponse(WebApi.ChybaWsdlService.Chybas[] chybas) {
            this.chybas = chybas;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insert", WrapperNamespace="http://labss2.fiit.stuba.sk/pis/students/team024chyba/types", IsWrapped=true)]
    public partial class insertRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024chyba/types", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string team_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024chyba/types", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string team_password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024chyba/types", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WebApi.ChybaWsdlService.Chyba Chyba;
        
        public insertRequest() {
        }
        
        public insertRequest(string team_id, string team_password, WebApi.ChybaWsdlService.Chyba Chyba) {
            this.team_id = team_id;
            this.team_password = team_password;
            this.Chyba = Chyba;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertResponse", WrapperNamespace="http://labss2.fiit.stuba.sk/pis/students/team024chyba/types", IsWrapped=true)]
    public partial class insertResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024chyba/types", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public insertResponse() {
        }
        
        public insertResponse(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="update", WrapperNamespace="http://labss2.fiit.stuba.sk/pis/students/team024chyba/types", IsWrapped=true)]
    public partial class updateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024chyba/types", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string team_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024chyba/types", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string team_password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024chyba/types", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int entity_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024chyba/types", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WebApi.ChybaWsdlService.Chyba Chyba;
        
        public updateRequest() {
        }
        
        public updateRequest(string team_id, string team_password, int entity_id, WebApi.ChybaWsdlService.Chyba Chyba) {
            this.team_id = team_id;
            this.team_password = team_password;
            this.entity_id = entity_id;
            this.Chyba = Chyba;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateResponse", WrapperNamespace="http://labss2.fiit.stuba.sk/pis/students/team024chyba/types", IsWrapped=true)]
    public partial class updateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024chyba/types", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int updates;
        
        public updateResponse() {
        }
        
        public updateResponse(int updates) {
            this.updates = updates;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="delete", WrapperNamespace="http://labss2.fiit.stuba.sk/pis/students/team024chyba/types", IsWrapped=true)]
    public partial class deleteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024chyba/types", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string team_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024chyba/types", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string team_password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024chyba/types", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int entity_id;
        
        public deleteRequest() {
        }
        
        public deleteRequest(string team_id, string team_password, int entity_id) {
            this.team_id = team_id;
            this.team_password = team_password;
            this.entity_id = entity_id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteResponse", WrapperNamespace="http://labss2.fiit.stuba.sk/pis/students/team024chyba/types", IsWrapped=true)]
    public partial class deleteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024chyba/types", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool deleted;
        
        public deleteResponse() {
        }
        
        public deleteResponse(bool deleted) {
            this.deleted = deleted;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Team024ChybaPortTypeChannel : WebApi.ChybaWsdlService.Team024ChybaPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Team024ChybaPortTypeClient : System.ServiceModel.ClientBase<WebApi.ChybaWsdlService.Team024ChybaPortType>, WebApi.ChybaWsdlService.Team024ChybaPortType {
        
        public Team024ChybaPortTypeClient() {
        }
        
        public Team024ChybaPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Team024ChybaPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Team024ChybaPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Team024ChybaPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApi.ChybaWsdlService.getByIdResponse WebApi.ChybaWsdlService.Team024ChybaPortType.getById(WebApi.ChybaWsdlService.getByIdRequest request) {
            return base.Channel.getById(request);
        }
        
        public WebApi.ChybaWsdlService.Chyba getById(int id) {
            WebApi.ChybaWsdlService.getByIdRequest inValue = new WebApi.ChybaWsdlService.getByIdRequest();
            inValue.id = id;
            WebApi.ChybaWsdlService.getByIdResponse retVal = ((WebApi.ChybaWsdlService.Team024ChybaPortType)(this)).getById(inValue);
            return retVal.chyba;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApi.ChybaWsdlService.getByIdResponse> WebApi.ChybaWsdlService.Team024ChybaPortType.getByIdAsync(WebApi.ChybaWsdlService.getByIdRequest request) {
            return base.Channel.getByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApi.ChybaWsdlService.getByIdResponse> getByIdAsync(int id) {
            WebApi.ChybaWsdlService.getByIdRequest inValue = new WebApi.ChybaWsdlService.getByIdRequest();
            inValue.id = id;
            return ((WebApi.ChybaWsdlService.Team024ChybaPortType)(this)).getByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApi.ChybaWsdlService.getByAttributeValueResponse WebApi.ChybaWsdlService.Team024ChybaPortType.getByAttributeValue(WebApi.ChybaWsdlService.getByAttributeValueRequest request) {
            return base.Channel.getByAttributeValue(request);
        }
        
        public WebApi.ChybaWsdlService.Chybas[] getByAttributeValue(string attribute_name, string attribute_value, System.Nullable<int>[] ids) {
            WebApi.ChybaWsdlService.getByAttributeValueRequest inValue = new WebApi.ChybaWsdlService.getByAttributeValueRequest();
            inValue.attribute_name = attribute_name;
            inValue.attribute_value = attribute_value;
            inValue.ids = ids;
            WebApi.ChybaWsdlService.getByAttributeValueResponse retVal = ((WebApi.ChybaWsdlService.Team024ChybaPortType)(this)).getByAttributeValue(inValue);
            return retVal.chybas;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApi.ChybaWsdlService.getByAttributeValueResponse> WebApi.ChybaWsdlService.Team024ChybaPortType.getByAttributeValueAsync(WebApi.ChybaWsdlService.getByAttributeValueRequest request) {
            return base.Channel.getByAttributeValueAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApi.ChybaWsdlService.getByAttributeValueResponse> getByAttributeValueAsync(string attribute_name, string attribute_value, System.Nullable<int>[] ids) {
            WebApi.ChybaWsdlService.getByAttributeValueRequest inValue = new WebApi.ChybaWsdlService.getByAttributeValueRequest();
            inValue.attribute_name = attribute_name;
            inValue.attribute_value = attribute_value;
            inValue.ids = ids;
            return ((WebApi.ChybaWsdlService.Team024ChybaPortType)(this)).getByAttributeValueAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApi.ChybaWsdlService.getByNumericConditionResponse WebApi.ChybaWsdlService.Team024ChybaPortType.getByNumericCondition(WebApi.ChybaWsdlService.getByNumericConditionRequest request) {
            return base.Channel.getByNumericCondition(request);
        }
        
        public WebApi.ChybaWsdlService.Chybas[] getByNumericCondition(string attribute_name, string attribute_value, string math_condition, System.Nullable<int>[] ids) {
            WebApi.ChybaWsdlService.getByNumericConditionRequest inValue = new WebApi.ChybaWsdlService.getByNumericConditionRequest();
            inValue.attribute_name = attribute_name;
            inValue.attribute_value = attribute_value;
            inValue.math_condition = math_condition;
            inValue.ids = ids;
            WebApi.ChybaWsdlService.getByNumericConditionResponse retVal = ((WebApi.ChybaWsdlService.Team024ChybaPortType)(this)).getByNumericCondition(inValue);
            return retVal.chybas;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApi.ChybaWsdlService.getByNumericConditionResponse> WebApi.ChybaWsdlService.Team024ChybaPortType.getByNumericConditionAsync(WebApi.ChybaWsdlService.getByNumericConditionRequest request) {
            return base.Channel.getByNumericConditionAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApi.ChybaWsdlService.getByNumericConditionResponse> getByNumericConditionAsync(string attribute_name, string attribute_value, string math_condition, System.Nullable<int>[] ids) {
            WebApi.ChybaWsdlService.getByNumericConditionRequest inValue = new WebApi.ChybaWsdlService.getByNumericConditionRequest();
            inValue.attribute_name = attribute_name;
            inValue.attribute_value = attribute_value;
            inValue.math_condition = math_condition;
            inValue.ids = ids;
            return ((WebApi.ChybaWsdlService.Team024ChybaPortType)(this)).getByNumericConditionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApi.ChybaWsdlService.getAllResponse WebApi.ChybaWsdlService.Team024ChybaPortType.getAll(WebApi.ChybaWsdlService.getAllRequest request) {
            return base.Channel.getAll(request);
        }
        
        public WebApi.ChybaWsdlService.Chybas[] getAll() {
            WebApi.ChybaWsdlService.getAllRequest inValue = new WebApi.ChybaWsdlService.getAllRequest();
            WebApi.ChybaWsdlService.getAllResponse retVal = ((WebApi.ChybaWsdlService.Team024ChybaPortType)(this)).getAll(inValue);
            return retVal.chybas;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApi.ChybaWsdlService.getAllResponse> WebApi.ChybaWsdlService.Team024ChybaPortType.getAllAsync(WebApi.ChybaWsdlService.getAllRequest request) {
            return base.Channel.getAllAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApi.ChybaWsdlService.getAllResponse> getAllAsync() {
            WebApi.ChybaWsdlService.getAllRequest inValue = new WebApi.ChybaWsdlService.getAllRequest();
            return ((WebApi.ChybaWsdlService.Team024ChybaPortType)(this)).getAllAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApi.ChybaWsdlService.insertResponse WebApi.ChybaWsdlService.Team024ChybaPortType.insert(WebApi.ChybaWsdlService.insertRequest request) {
            return base.Channel.insert(request);
        }
        
        public int insert(string team_id, string team_password, WebApi.ChybaWsdlService.Chyba Chyba) {
            WebApi.ChybaWsdlService.insertRequest inValue = new WebApi.ChybaWsdlService.insertRequest();
            inValue.team_id = team_id;
            inValue.team_password = team_password;
            inValue.Chyba = Chyba;
            WebApi.ChybaWsdlService.insertResponse retVal = ((WebApi.ChybaWsdlService.Team024ChybaPortType)(this)).insert(inValue);
            return retVal.id;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApi.ChybaWsdlService.insertResponse> WebApi.ChybaWsdlService.Team024ChybaPortType.insertAsync(WebApi.ChybaWsdlService.insertRequest request) {
            return base.Channel.insertAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApi.ChybaWsdlService.insertResponse> insertAsync(string team_id, string team_password, WebApi.ChybaWsdlService.Chyba Chyba) {
            WebApi.ChybaWsdlService.insertRequest inValue = new WebApi.ChybaWsdlService.insertRequest();
            inValue.team_id = team_id;
            inValue.team_password = team_password;
            inValue.Chyba = Chyba;
            return ((WebApi.ChybaWsdlService.Team024ChybaPortType)(this)).insertAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApi.ChybaWsdlService.updateResponse WebApi.ChybaWsdlService.Team024ChybaPortType.update(WebApi.ChybaWsdlService.updateRequest request) {
            return base.Channel.update(request);
        }
        
        public int update(string team_id, string team_password, int entity_id, WebApi.ChybaWsdlService.Chyba Chyba) {
            WebApi.ChybaWsdlService.updateRequest inValue = new WebApi.ChybaWsdlService.updateRequest();
            inValue.team_id = team_id;
            inValue.team_password = team_password;
            inValue.entity_id = entity_id;
            inValue.Chyba = Chyba;
            WebApi.ChybaWsdlService.updateResponse retVal = ((WebApi.ChybaWsdlService.Team024ChybaPortType)(this)).update(inValue);
            return retVal.updates;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApi.ChybaWsdlService.updateResponse> WebApi.ChybaWsdlService.Team024ChybaPortType.updateAsync(WebApi.ChybaWsdlService.updateRequest request) {
            return base.Channel.updateAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApi.ChybaWsdlService.updateResponse> updateAsync(string team_id, string team_password, int entity_id, WebApi.ChybaWsdlService.Chyba Chyba) {
            WebApi.ChybaWsdlService.updateRequest inValue = new WebApi.ChybaWsdlService.updateRequest();
            inValue.team_id = team_id;
            inValue.team_password = team_password;
            inValue.entity_id = entity_id;
            inValue.Chyba = Chyba;
            return ((WebApi.ChybaWsdlService.Team024ChybaPortType)(this)).updateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApi.ChybaWsdlService.deleteResponse WebApi.ChybaWsdlService.Team024ChybaPortType.delete(WebApi.ChybaWsdlService.deleteRequest request) {
            return base.Channel.delete(request);
        }
        
        public bool delete(string team_id, string team_password, int entity_id) {
            WebApi.ChybaWsdlService.deleteRequest inValue = new WebApi.ChybaWsdlService.deleteRequest();
            inValue.team_id = team_id;
            inValue.team_password = team_password;
            inValue.entity_id = entity_id;
            WebApi.ChybaWsdlService.deleteResponse retVal = ((WebApi.ChybaWsdlService.Team024ChybaPortType)(this)).delete(inValue);
            return retVal.deleted;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApi.ChybaWsdlService.deleteResponse> WebApi.ChybaWsdlService.Team024ChybaPortType.deleteAsync(WebApi.ChybaWsdlService.deleteRequest request) {
            return base.Channel.deleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApi.ChybaWsdlService.deleteResponse> deleteAsync(string team_id, string team_password, int entity_id) {
            WebApi.ChybaWsdlService.deleteRequest inValue = new WebApi.ChybaWsdlService.deleteRequest();
            inValue.team_id = team_id;
            inValue.team_password = team_password;
            inValue.entity_id = entity_id;
            return ((WebApi.ChybaWsdlService.Team024ChybaPortType)(this)).deleteAsync(inValue);
        }
    }
}
