//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.VytlacokWsdlReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024vytlacok", ConfigurationName="VytlacokWsdlReference.Team024VytlacokPortType")]
    public interface Team024VytlacokPortType {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://labss2.fiit.stuba.sk/pis/students/team024vytlacok/types) of message getByIdRequest does not match the default value (http://labss2.fiit.stuba.sk/pis/students/team024vytlacok)
        [System.ServiceModel.OperationContractAttribute(Action="http://labss2.fiit.stuba.sk/pis/students/team024vytlacok/#getById", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebApi.VytlacokWsdlReference.getByIdResponse getById(WebApi.VytlacokWsdlReference.getByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://labss2.fiit.stuba.sk/pis/students/team024vytlacok/#getById", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApi.VytlacokWsdlReference.getByIdResponse> getByIdAsync(WebApi.VytlacokWsdlReference.getByIdRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://labss2.fiit.stuba.sk/pis/students/team024vytlacok/types) of message getByAttributeValueRequest does not match the default value (http://labss2.fiit.stuba.sk/pis/students/team024vytlacok)
        [System.ServiceModel.OperationContractAttribute(Action="http://labss2.fiit.stuba.sk/pis/students/team024vytlacok/#getByAttributeValue", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebApi.VytlacokWsdlReference.getByAttributeValueResponse getByAttributeValue(WebApi.VytlacokWsdlReference.getByAttributeValueRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://labss2.fiit.stuba.sk/pis/students/team024vytlacok/#getByAttributeValue", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApi.VytlacokWsdlReference.getByAttributeValueResponse> getByAttributeValueAsync(WebApi.VytlacokWsdlReference.getByAttributeValueRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://labss2.fiit.stuba.sk/pis/students/team024vytlacok/types) of message getByNumericConditionRequest does not match the default value (http://labss2.fiit.stuba.sk/pis/students/team024vytlacok)
        [System.ServiceModel.OperationContractAttribute(Action="http://labss2.fiit.stuba.sk/pis/students/team024vytlacok/#getByNumericCondition", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebApi.VytlacokWsdlReference.getByNumericConditionResponse getByNumericCondition(WebApi.VytlacokWsdlReference.getByNumericConditionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://labss2.fiit.stuba.sk/pis/students/team024vytlacok/#getByNumericCondition", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApi.VytlacokWsdlReference.getByNumericConditionResponse> getByNumericConditionAsync(WebApi.VytlacokWsdlReference.getByNumericConditionRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://labss2.fiit.stuba.sk/pis/students/team024vytlacok/types) of message getAllRequest does not match the default value (http://labss2.fiit.stuba.sk/pis/students/team024vytlacok)
        [System.ServiceModel.OperationContractAttribute(Action="http://labss2.fiit.stuba.sk/pis/students/team024vytlacok/#getAll", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebApi.VytlacokWsdlReference.getAllResponse getAll(WebApi.VytlacokWsdlReference.getAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://labss2.fiit.stuba.sk/pis/students/team024vytlacok/#getAll", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApi.VytlacokWsdlReference.getAllResponse> getAllAsync(WebApi.VytlacokWsdlReference.getAllRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://labss2.fiit.stuba.sk/pis/students/team024vytlacok/types) of message insertRequest does not match the default value (http://labss2.fiit.stuba.sk/pis/students/team024vytlacok)
        [System.ServiceModel.OperationContractAttribute(Action="http://labss2.fiit.stuba.sk/pis/students/team024vytlacok/#insert", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebApi.VytlacokWsdlReference.insertResponse insert(WebApi.VytlacokWsdlReference.insertRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://labss2.fiit.stuba.sk/pis/students/team024vytlacok/#insert", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApi.VytlacokWsdlReference.insertResponse> insertAsync(WebApi.VytlacokWsdlReference.insertRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://labss2.fiit.stuba.sk/pis/students/team024vytlacok/types) of message updateRequest does not match the default value (http://labss2.fiit.stuba.sk/pis/students/team024vytlacok)
        [System.ServiceModel.OperationContractAttribute(Action="http://labss2.fiit.stuba.sk/pis/students/team024vytlacok/#update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebApi.VytlacokWsdlReference.updateResponse update(WebApi.VytlacokWsdlReference.updateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://labss2.fiit.stuba.sk/pis/students/team024vytlacok/#update", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApi.VytlacokWsdlReference.updateResponse> updateAsync(WebApi.VytlacokWsdlReference.updateRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://labss2.fiit.stuba.sk/pis/students/team024vytlacok/types) of message deleteRequest does not match the default value (http://labss2.fiit.stuba.sk/pis/students/team024vytlacok)
        [System.ServiceModel.OperationContractAttribute(Action="http://labss2.fiit.stuba.sk/pis/students/team024vytlacok/#delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebApi.VytlacokWsdlReference.deleteResponse delete(WebApi.VytlacokWsdlReference.deleteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://labss2.fiit.stuba.sk/pis/students/team024vytlacok/#delete", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApi.VytlacokWsdlReference.deleteResponse> deleteAsync(WebApi.VytlacokWsdlReference.deleteRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024vytlacok/types")]
    public partial class Vytlacok : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string nameField;
        
        private int kniha_idField;
        
        private string vydavatelstvoField;
        
        private int pocetStranField;
        
        private string typVazbyField;
        
        private string formatVydaniaField;
        
        private string jazykField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int kniha_id {
            get {
                return this.kniha_idField;
            }
            set {
                this.kniha_idField = value;
                this.RaisePropertyChanged("kniha_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string vydavatelstvo {
            get {
                return this.vydavatelstvoField;
            }
            set {
                this.vydavatelstvoField = value;
                this.RaisePropertyChanged("vydavatelstvo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int pocetStran {
            get {
                return this.pocetStranField;
            }
            set {
                this.pocetStranField = value;
                this.RaisePropertyChanged("pocetStran");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string typVazby {
            get {
                return this.typVazbyField;
            }
            set {
                this.typVazbyField = value;
                this.RaisePropertyChanged("typVazby");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string formatVydania {
            get {
                return this.formatVydaniaField;
            }
            set {
                this.formatVydaniaField = value;
                this.RaisePropertyChanged("formatVydania");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string jazyk {
            get {
                return this.jazykField;
            }
            set {
                this.jazykField = value;
                this.RaisePropertyChanged("jazyk");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024vytlacok/types")]
    public partial class Vytlacoks : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string nameField;
        
        private int kniha_idField;
        
        private string vydavatelstvoField;
        
        private int pocetStranField;
        
        private string typVazbyField;
        
        private string formatVydaniaField;
        
        private string jazykField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int kniha_id {
            get {
                return this.kniha_idField;
            }
            set {
                this.kniha_idField = value;
                this.RaisePropertyChanged("kniha_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string vydavatelstvo {
            get {
                return this.vydavatelstvoField;
            }
            set {
                this.vydavatelstvoField = value;
                this.RaisePropertyChanged("vydavatelstvo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int pocetStran {
            get {
                return this.pocetStranField;
            }
            set {
                this.pocetStranField = value;
                this.RaisePropertyChanged("pocetStran");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string typVazby {
            get {
                return this.typVazbyField;
            }
            set {
                this.typVazbyField = value;
                this.RaisePropertyChanged("typVazby");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string formatVydania {
            get {
                return this.formatVydaniaField;
            }
            set {
                this.formatVydaniaField = value;
                this.RaisePropertyChanged("formatVydania");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string jazyk {
            get {
                return this.jazykField;
            }
            set {
                this.jazykField = value;
                this.RaisePropertyChanged("jazyk");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getById", WrapperNamespace="http://labss2.fiit.stuba.sk/pis/students/team024vytlacok/types", IsWrapped=true)]
    public partial class getByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024vytlacok/types", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public getByIdRequest() {
        }
        
        public getByIdRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getByIdResponse", WrapperNamespace="http://labss2.fiit.stuba.sk/pis/students/team024vytlacok/types", IsWrapped=true)]
    public partial class getByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024vytlacok/types", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WebApi.VytlacokWsdlReference.Vytlacok vytlacok;
        
        public getByIdResponse() {
        }
        
        public getByIdResponse(WebApi.VytlacokWsdlReference.Vytlacok vytlacok) {
            this.vytlacok = vytlacok;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getByAttributeValue", WrapperNamespace="http://labss2.fiit.stuba.sk/pis/students/team024vytlacok/types", IsWrapped=true)]
    public partial class getByAttributeValueRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024vytlacok/types", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string attribute_name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024vytlacok/types", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string attribute_value;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024vytlacok/types", Order=2)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("id", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Nullable<int>[] ids;
        
        public getByAttributeValueRequest() {
        }
        
        public getByAttributeValueRequest(string attribute_name, string attribute_value, System.Nullable<int>[] ids) {
            this.attribute_name = attribute_name;
            this.attribute_value = attribute_value;
            this.ids = ids;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getByAttributeValueResponse", WrapperNamespace="http://labss2.fiit.stuba.sk/pis/students/team024vytlacok/types", IsWrapped=true)]
    public partial class getByAttributeValueResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024vytlacok/types", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("vytlacok", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WebApi.VytlacokWsdlReference.Vytlacoks[] vytlacoks;
        
        public getByAttributeValueResponse() {
        }
        
        public getByAttributeValueResponse(WebApi.VytlacokWsdlReference.Vytlacoks[] vytlacoks) {
            this.vytlacoks = vytlacoks;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getByNumericCondition", WrapperNamespace="http://labss2.fiit.stuba.sk/pis/students/team024vytlacok/types", IsWrapped=true)]
    public partial class getByNumericConditionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024vytlacok/types", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string attribute_name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024vytlacok/types", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string attribute_value;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024vytlacok/types", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string math_condition;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024vytlacok/types", Order=3)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("id", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Nullable<int>[] ids;
        
        public getByNumericConditionRequest() {
        }
        
        public getByNumericConditionRequest(string attribute_name, string attribute_value, string math_condition, System.Nullable<int>[] ids) {
            this.attribute_name = attribute_name;
            this.attribute_value = attribute_value;
            this.math_condition = math_condition;
            this.ids = ids;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getByNumericConditionResponse", WrapperNamespace="http://labss2.fiit.stuba.sk/pis/students/team024vytlacok/types", IsWrapped=true)]
    public partial class getByNumericConditionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024vytlacok/types", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("vytlacok", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WebApi.VytlacokWsdlReference.Vytlacoks[] vytlacoks;
        
        public getByNumericConditionResponse() {
        }
        
        public getByNumericConditionResponse(WebApi.VytlacokWsdlReference.Vytlacoks[] vytlacoks) {
            this.vytlacoks = vytlacoks;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAll", WrapperNamespace="http://labss2.fiit.stuba.sk/pis/students/team024vytlacok/types", IsWrapped=true)]
    public partial class getAllRequest {
        
        public getAllRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllResponse", WrapperNamespace="http://labss2.fiit.stuba.sk/pis/students/team024vytlacok/types", IsWrapped=true)]
    public partial class getAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024vytlacok/types", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("vytlacok", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WebApi.VytlacokWsdlReference.Vytlacoks[] vytlacoks;
        
        public getAllResponse() {
        }
        
        public getAllResponse(WebApi.VytlacokWsdlReference.Vytlacoks[] vytlacoks) {
            this.vytlacoks = vytlacoks;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insert", WrapperNamespace="http://labss2.fiit.stuba.sk/pis/students/team024vytlacok/types", IsWrapped=true)]
    public partial class insertRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024vytlacok/types", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string team_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024vytlacok/types", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string team_password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024vytlacok/types", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WebApi.VytlacokWsdlReference.Vytlacok Vytlacok;
        
        public insertRequest() {
        }
        
        public insertRequest(string team_id, string team_password, WebApi.VytlacokWsdlReference.Vytlacok Vytlacok) {
            this.team_id = team_id;
            this.team_password = team_password;
            this.Vytlacok = Vytlacok;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertResponse", WrapperNamespace="http://labss2.fiit.stuba.sk/pis/students/team024vytlacok/types", IsWrapped=true)]
    public partial class insertResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024vytlacok/types", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public insertResponse() {
        }
        
        public insertResponse(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="update", WrapperNamespace="http://labss2.fiit.stuba.sk/pis/students/team024vytlacok/types", IsWrapped=true)]
    public partial class updateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024vytlacok/types", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string team_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024vytlacok/types", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string team_password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024vytlacok/types", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int entity_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024vytlacok/types", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WebApi.VytlacokWsdlReference.Vytlacok Vytlacok;
        
        public updateRequest() {
        }
        
        public updateRequest(string team_id, string team_password, int entity_id, WebApi.VytlacokWsdlReference.Vytlacok Vytlacok) {
            this.team_id = team_id;
            this.team_password = team_password;
            this.entity_id = entity_id;
            this.Vytlacok = Vytlacok;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateResponse", WrapperNamespace="http://labss2.fiit.stuba.sk/pis/students/team024vytlacok/types", IsWrapped=true)]
    public partial class updateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024vytlacok/types", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int updates;
        
        public updateResponse() {
        }
        
        public updateResponse(int updates) {
            this.updates = updates;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="delete", WrapperNamespace="http://labss2.fiit.stuba.sk/pis/students/team024vytlacok/types", IsWrapped=true)]
    public partial class deleteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024vytlacok/types", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string team_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024vytlacok/types", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string team_password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024vytlacok/types", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int entity_id;
        
        public deleteRequest() {
        }
        
        public deleteRequest(string team_id, string team_password, int entity_id) {
            this.team_id = team_id;
            this.team_password = team_password;
            this.entity_id = entity_id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteResponse", WrapperNamespace="http://labss2.fiit.stuba.sk/pis/students/team024vytlacok/types", IsWrapped=true)]
    public partial class deleteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024vytlacok/types", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool deleted;
        
        public deleteResponse() {
        }
        
        public deleteResponse(bool deleted) {
            this.deleted = deleted;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Team024VytlacokPortTypeChannel : WebApi.VytlacokWsdlReference.Team024VytlacokPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Team024VytlacokPortTypeClient : System.ServiceModel.ClientBase<WebApi.VytlacokWsdlReference.Team024VytlacokPortType>, WebApi.VytlacokWsdlReference.Team024VytlacokPortType {
        
        public Team024VytlacokPortTypeClient() {
        }
        
        public Team024VytlacokPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Team024VytlacokPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Team024VytlacokPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Team024VytlacokPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApi.VytlacokWsdlReference.getByIdResponse WebApi.VytlacokWsdlReference.Team024VytlacokPortType.getById(WebApi.VytlacokWsdlReference.getByIdRequest request) {
            return base.Channel.getById(request);
        }
        
        public WebApi.VytlacokWsdlReference.Vytlacok getById(int id) {
            WebApi.VytlacokWsdlReference.getByIdRequest inValue = new WebApi.VytlacokWsdlReference.getByIdRequest();
            inValue.id = id;
            WebApi.VytlacokWsdlReference.getByIdResponse retVal = ((WebApi.VytlacokWsdlReference.Team024VytlacokPortType)(this)).getById(inValue);
            return retVal.vytlacok;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApi.VytlacokWsdlReference.getByIdResponse> WebApi.VytlacokWsdlReference.Team024VytlacokPortType.getByIdAsync(WebApi.VytlacokWsdlReference.getByIdRequest request) {
            return base.Channel.getByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApi.VytlacokWsdlReference.getByIdResponse> getByIdAsync(int id) {
            WebApi.VytlacokWsdlReference.getByIdRequest inValue = new WebApi.VytlacokWsdlReference.getByIdRequest();
            inValue.id = id;
            return ((WebApi.VytlacokWsdlReference.Team024VytlacokPortType)(this)).getByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApi.VytlacokWsdlReference.getByAttributeValueResponse WebApi.VytlacokWsdlReference.Team024VytlacokPortType.getByAttributeValue(WebApi.VytlacokWsdlReference.getByAttributeValueRequest request) {
            return base.Channel.getByAttributeValue(request);
        }
        
        public WebApi.VytlacokWsdlReference.Vytlacoks[] getByAttributeValue(string attribute_name, string attribute_value, System.Nullable<int>[] ids) {
            WebApi.VytlacokWsdlReference.getByAttributeValueRequest inValue = new WebApi.VytlacokWsdlReference.getByAttributeValueRequest();
            inValue.attribute_name = attribute_name;
            inValue.attribute_value = attribute_value;
            inValue.ids = ids;
            WebApi.VytlacokWsdlReference.getByAttributeValueResponse retVal = ((WebApi.VytlacokWsdlReference.Team024VytlacokPortType)(this)).getByAttributeValue(inValue);
            return retVal.vytlacoks;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApi.VytlacokWsdlReference.getByAttributeValueResponse> WebApi.VytlacokWsdlReference.Team024VytlacokPortType.getByAttributeValueAsync(WebApi.VytlacokWsdlReference.getByAttributeValueRequest request) {
            return base.Channel.getByAttributeValueAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApi.VytlacokWsdlReference.getByAttributeValueResponse> getByAttributeValueAsync(string attribute_name, string attribute_value, System.Nullable<int>[] ids) {
            WebApi.VytlacokWsdlReference.getByAttributeValueRequest inValue = new WebApi.VytlacokWsdlReference.getByAttributeValueRequest();
            inValue.attribute_name = attribute_name;
            inValue.attribute_value = attribute_value;
            inValue.ids = ids;
            return ((WebApi.VytlacokWsdlReference.Team024VytlacokPortType)(this)).getByAttributeValueAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApi.VytlacokWsdlReference.getByNumericConditionResponse WebApi.VytlacokWsdlReference.Team024VytlacokPortType.getByNumericCondition(WebApi.VytlacokWsdlReference.getByNumericConditionRequest request) {
            return base.Channel.getByNumericCondition(request);
        }
        
        public WebApi.VytlacokWsdlReference.Vytlacoks[] getByNumericCondition(string attribute_name, string attribute_value, string math_condition, System.Nullable<int>[] ids) {
            WebApi.VytlacokWsdlReference.getByNumericConditionRequest inValue = new WebApi.VytlacokWsdlReference.getByNumericConditionRequest();
            inValue.attribute_name = attribute_name;
            inValue.attribute_value = attribute_value;
            inValue.math_condition = math_condition;
            inValue.ids = ids;
            WebApi.VytlacokWsdlReference.getByNumericConditionResponse retVal = ((WebApi.VytlacokWsdlReference.Team024VytlacokPortType)(this)).getByNumericCondition(inValue);
            return retVal.vytlacoks;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApi.VytlacokWsdlReference.getByNumericConditionResponse> WebApi.VytlacokWsdlReference.Team024VytlacokPortType.getByNumericConditionAsync(WebApi.VytlacokWsdlReference.getByNumericConditionRequest request) {
            return base.Channel.getByNumericConditionAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApi.VytlacokWsdlReference.getByNumericConditionResponse> getByNumericConditionAsync(string attribute_name, string attribute_value, string math_condition, System.Nullable<int>[] ids) {
            WebApi.VytlacokWsdlReference.getByNumericConditionRequest inValue = new WebApi.VytlacokWsdlReference.getByNumericConditionRequest();
            inValue.attribute_name = attribute_name;
            inValue.attribute_value = attribute_value;
            inValue.math_condition = math_condition;
            inValue.ids = ids;
            return ((WebApi.VytlacokWsdlReference.Team024VytlacokPortType)(this)).getByNumericConditionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApi.VytlacokWsdlReference.getAllResponse WebApi.VytlacokWsdlReference.Team024VytlacokPortType.getAll(WebApi.VytlacokWsdlReference.getAllRequest request) {
            return base.Channel.getAll(request);
        }
        
        public WebApi.VytlacokWsdlReference.Vytlacoks[] getAll() {
            WebApi.VytlacokWsdlReference.getAllRequest inValue = new WebApi.VytlacokWsdlReference.getAllRequest();
            WebApi.VytlacokWsdlReference.getAllResponse retVal = ((WebApi.VytlacokWsdlReference.Team024VytlacokPortType)(this)).getAll(inValue);
            return retVal.vytlacoks;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApi.VytlacokWsdlReference.getAllResponse> WebApi.VytlacokWsdlReference.Team024VytlacokPortType.getAllAsync(WebApi.VytlacokWsdlReference.getAllRequest request) {
            return base.Channel.getAllAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApi.VytlacokWsdlReference.getAllResponse> getAllAsync() {
            WebApi.VytlacokWsdlReference.getAllRequest inValue = new WebApi.VytlacokWsdlReference.getAllRequest();
            return ((WebApi.VytlacokWsdlReference.Team024VytlacokPortType)(this)).getAllAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApi.VytlacokWsdlReference.insertResponse WebApi.VytlacokWsdlReference.Team024VytlacokPortType.insert(WebApi.VytlacokWsdlReference.insertRequest request) {
            return base.Channel.insert(request);
        }
        
        public int insert(string team_id, string team_password, WebApi.VytlacokWsdlReference.Vytlacok Vytlacok) {
            WebApi.VytlacokWsdlReference.insertRequest inValue = new WebApi.VytlacokWsdlReference.insertRequest();
            inValue.team_id = team_id;
            inValue.team_password = team_password;
            inValue.Vytlacok = Vytlacok;
            WebApi.VytlacokWsdlReference.insertResponse retVal = ((WebApi.VytlacokWsdlReference.Team024VytlacokPortType)(this)).insert(inValue);
            return retVal.id;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApi.VytlacokWsdlReference.insertResponse> WebApi.VytlacokWsdlReference.Team024VytlacokPortType.insertAsync(WebApi.VytlacokWsdlReference.insertRequest request) {
            return base.Channel.insertAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApi.VytlacokWsdlReference.insertResponse> insertAsync(string team_id, string team_password, WebApi.VytlacokWsdlReference.Vytlacok Vytlacok) {
            WebApi.VytlacokWsdlReference.insertRequest inValue = new WebApi.VytlacokWsdlReference.insertRequest();
            inValue.team_id = team_id;
            inValue.team_password = team_password;
            inValue.Vytlacok = Vytlacok;
            return ((WebApi.VytlacokWsdlReference.Team024VytlacokPortType)(this)).insertAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApi.VytlacokWsdlReference.updateResponse WebApi.VytlacokWsdlReference.Team024VytlacokPortType.update(WebApi.VytlacokWsdlReference.updateRequest request) {
            return base.Channel.update(request);
        }
        
        public int update(string team_id, string team_password, int entity_id, WebApi.VytlacokWsdlReference.Vytlacok Vytlacok) {
            WebApi.VytlacokWsdlReference.updateRequest inValue = new WebApi.VytlacokWsdlReference.updateRequest();
            inValue.team_id = team_id;
            inValue.team_password = team_password;
            inValue.entity_id = entity_id;
            inValue.Vytlacok = Vytlacok;
            WebApi.VytlacokWsdlReference.updateResponse retVal = ((WebApi.VytlacokWsdlReference.Team024VytlacokPortType)(this)).update(inValue);
            return retVal.updates;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApi.VytlacokWsdlReference.updateResponse> WebApi.VytlacokWsdlReference.Team024VytlacokPortType.updateAsync(WebApi.VytlacokWsdlReference.updateRequest request) {
            return base.Channel.updateAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApi.VytlacokWsdlReference.updateResponse> updateAsync(string team_id, string team_password, int entity_id, WebApi.VytlacokWsdlReference.Vytlacok Vytlacok) {
            WebApi.VytlacokWsdlReference.updateRequest inValue = new WebApi.VytlacokWsdlReference.updateRequest();
            inValue.team_id = team_id;
            inValue.team_password = team_password;
            inValue.entity_id = entity_id;
            inValue.Vytlacok = Vytlacok;
            return ((WebApi.VytlacokWsdlReference.Team024VytlacokPortType)(this)).updateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApi.VytlacokWsdlReference.deleteResponse WebApi.VytlacokWsdlReference.Team024VytlacokPortType.delete(WebApi.VytlacokWsdlReference.deleteRequest request) {
            return base.Channel.delete(request);
        }
        
        public bool delete(string team_id, string team_password, int entity_id) {
            WebApi.VytlacokWsdlReference.deleteRequest inValue = new WebApi.VytlacokWsdlReference.deleteRequest();
            inValue.team_id = team_id;
            inValue.team_password = team_password;
            inValue.entity_id = entity_id;
            WebApi.VytlacokWsdlReference.deleteResponse retVal = ((WebApi.VytlacokWsdlReference.Team024VytlacokPortType)(this)).delete(inValue);
            return retVal.deleted;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApi.VytlacokWsdlReference.deleteResponse> WebApi.VytlacokWsdlReference.Team024VytlacokPortType.deleteAsync(WebApi.VytlacokWsdlReference.deleteRequest request) {
            return base.Channel.deleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApi.VytlacokWsdlReference.deleteResponse> deleteAsync(string team_id, string team_password, int entity_id) {
            WebApi.VytlacokWsdlReference.deleteRequest inValue = new WebApi.VytlacokWsdlReference.deleteRequest();
            inValue.team_id = team_id;
            inValue.team_password = team_password;
            inValue.entity_id = entity_id;
            return ((WebApi.VytlacokWsdlReference.Team024VytlacokPortType)(this)).deleteAsync(inValue);
        }
    }
}
