//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.PouzivatelWsdlService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024pouzivatel", ConfigurationName="PouzivatelWsdlService.Team024PouzivatelPortType")]
    public interface Team024PouzivatelPortType {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://labss2.fiit.stuba.sk/pis/students/team024pouzivatel/types) of message getByIdRequest does not match the default value (http://labss2.fiit.stuba.sk/pis/students/team024pouzivatel)
        [System.ServiceModel.OperationContractAttribute(Action="http://labss2.fiit.stuba.sk/pis/students/team024pouzivatel/#getById", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebApi.PouzivatelWsdlService.getByIdResponse getById(WebApi.PouzivatelWsdlService.getByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://labss2.fiit.stuba.sk/pis/students/team024pouzivatel/#getById", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApi.PouzivatelWsdlService.getByIdResponse> getByIdAsync(WebApi.PouzivatelWsdlService.getByIdRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://labss2.fiit.stuba.sk/pis/students/team024pouzivatel/types) of message getByAttributeValueRequest does not match the default value (http://labss2.fiit.stuba.sk/pis/students/team024pouzivatel)
        [System.ServiceModel.OperationContractAttribute(Action="http://labss2.fiit.stuba.sk/pis/students/team024pouzivatel/#getByAttributeValue", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebApi.PouzivatelWsdlService.getByAttributeValueResponse getByAttributeValue(WebApi.PouzivatelWsdlService.getByAttributeValueRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://labss2.fiit.stuba.sk/pis/students/team024pouzivatel/#getByAttributeValue", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApi.PouzivatelWsdlService.getByAttributeValueResponse> getByAttributeValueAsync(WebApi.PouzivatelWsdlService.getByAttributeValueRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://labss2.fiit.stuba.sk/pis/students/team024pouzivatel/types) of message getByNumericConditionRequest does not match the default value (http://labss2.fiit.stuba.sk/pis/students/team024pouzivatel)
        [System.ServiceModel.OperationContractAttribute(Action="http://labss2.fiit.stuba.sk/pis/students/team024pouzivatel/#getByNumericCondition" +
            "", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebApi.PouzivatelWsdlService.getByNumericConditionResponse getByNumericCondition(WebApi.PouzivatelWsdlService.getByNumericConditionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://labss2.fiit.stuba.sk/pis/students/team024pouzivatel/#getByNumericCondition" +
            "", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApi.PouzivatelWsdlService.getByNumericConditionResponse> getByNumericConditionAsync(WebApi.PouzivatelWsdlService.getByNumericConditionRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://labss2.fiit.stuba.sk/pis/students/team024pouzivatel/types) of message getAllRequest does not match the default value (http://labss2.fiit.stuba.sk/pis/students/team024pouzivatel)
        [System.ServiceModel.OperationContractAttribute(Action="http://labss2.fiit.stuba.sk/pis/students/team024pouzivatel/#getAll", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebApi.PouzivatelWsdlService.getAllResponse getAll(WebApi.PouzivatelWsdlService.getAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://labss2.fiit.stuba.sk/pis/students/team024pouzivatel/#getAll", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApi.PouzivatelWsdlService.getAllResponse> getAllAsync(WebApi.PouzivatelWsdlService.getAllRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://labss2.fiit.stuba.sk/pis/students/team024pouzivatel/types) of message insertRequest does not match the default value (http://labss2.fiit.stuba.sk/pis/students/team024pouzivatel)
        [System.ServiceModel.OperationContractAttribute(Action="http://labss2.fiit.stuba.sk/pis/students/team024pouzivatel/#insert", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebApi.PouzivatelWsdlService.insertResponse insert(WebApi.PouzivatelWsdlService.insertRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://labss2.fiit.stuba.sk/pis/students/team024pouzivatel/#insert", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApi.PouzivatelWsdlService.insertResponse> insertAsync(WebApi.PouzivatelWsdlService.insertRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://labss2.fiit.stuba.sk/pis/students/team024pouzivatel/types) of message updateRequest does not match the default value (http://labss2.fiit.stuba.sk/pis/students/team024pouzivatel)
        [System.ServiceModel.OperationContractAttribute(Action="http://labss2.fiit.stuba.sk/pis/students/team024pouzivatel/#update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebApi.PouzivatelWsdlService.updateResponse update(WebApi.PouzivatelWsdlService.updateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://labss2.fiit.stuba.sk/pis/students/team024pouzivatel/#update", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApi.PouzivatelWsdlService.updateResponse> updateAsync(WebApi.PouzivatelWsdlService.updateRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://labss2.fiit.stuba.sk/pis/students/team024pouzivatel/types) of message deleteRequest does not match the default value (http://labss2.fiit.stuba.sk/pis/students/team024pouzivatel)
        [System.ServiceModel.OperationContractAttribute(Action="http://labss2.fiit.stuba.sk/pis/students/team024pouzivatel/#delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebApi.PouzivatelWsdlService.deleteResponse delete(WebApi.PouzivatelWsdlService.deleteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://labss2.fiit.stuba.sk/pis/students/team024pouzivatel/#delete", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApi.PouzivatelWsdlService.deleteResponse> deleteAsync(WebApi.PouzivatelWsdlService.deleteRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024pouzivatel/types")]
    public partial class Pouzivatel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string nameField;
        
        private string emailField;
        
        private int bodyField;
        
        private int rolaField;
        
        private System.DateTime datRegistracieField;
        
        private System.DateTime poslednePrihlasenieField;
        
        private string hesloField;
        
        private string prihlasovacieMenoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int body {
            get {
                return this.bodyField;
            }
            set {
                this.bodyField = value;
                this.RaisePropertyChanged("body");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int rola {
            get {
                return this.rolaField;
            }
            set {
                this.rolaField = value;
                this.RaisePropertyChanged("rola");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public System.DateTime datRegistracie {
            get {
                return this.datRegistracieField;
            }
            set {
                this.datRegistracieField = value;
                this.RaisePropertyChanged("datRegistracie");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public System.DateTime poslednePrihlasenie {
            get {
                return this.poslednePrihlasenieField;
            }
            set {
                this.poslednePrihlasenieField = value;
                this.RaisePropertyChanged("poslednePrihlasenie");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string heslo {
            get {
                return this.hesloField;
            }
            set {
                this.hesloField = value;
                this.RaisePropertyChanged("heslo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string prihlasovacieMeno {
            get {
                return this.prihlasovacieMenoField;
            }
            set {
                this.prihlasovacieMenoField = value;
                this.RaisePropertyChanged("prihlasovacieMeno");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024pouzivatel/types")]
    public partial class Pouzivatels : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string nameField;
        
        private string emailField;
        
        private int bodyField;
        
        private int rolaField;
        
        private System.DateTime datRegistracieField;
        
        private System.DateTime poslednePrihlasenieField;
        
        private string hesloField;
        
        private string prihlasovacieMenoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int body {
            get {
                return this.bodyField;
            }
            set {
                this.bodyField = value;
                this.RaisePropertyChanged("body");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int rola {
            get {
                return this.rolaField;
            }
            set {
                this.rolaField = value;
                this.RaisePropertyChanged("rola");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public System.DateTime datRegistracie {
            get {
                return this.datRegistracieField;
            }
            set {
                this.datRegistracieField = value;
                this.RaisePropertyChanged("datRegistracie");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public System.DateTime poslednePrihlasenie {
            get {
                return this.poslednePrihlasenieField;
            }
            set {
                this.poslednePrihlasenieField = value;
                this.RaisePropertyChanged("poslednePrihlasenie");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string heslo {
            get {
                return this.hesloField;
            }
            set {
                this.hesloField = value;
                this.RaisePropertyChanged("heslo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string prihlasovacieMeno {
            get {
                return this.prihlasovacieMenoField;
            }
            set {
                this.prihlasovacieMenoField = value;
                this.RaisePropertyChanged("prihlasovacieMeno");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getById", WrapperNamespace="http://labss2.fiit.stuba.sk/pis/students/team024pouzivatel/types", IsWrapped=true)]
    public partial class getByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024pouzivatel/types", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public getByIdRequest() {
        }
        
        public getByIdRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getByIdResponse", WrapperNamespace="http://labss2.fiit.stuba.sk/pis/students/team024pouzivatel/types", IsWrapped=true)]
    public partial class getByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024pouzivatel/types", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WebApi.PouzivatelWsdlService.Pouzivatel pouzivatel;
        
        public getByIdResponse() {
        }
        
        public getByIdResponse(WebApi.PouzivatelWsdlService.Pouzivatel pouzivatel) {
            this.pouzivatel = pouzivatel;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getByAttributeValue", WrapperNamespace="http://labss2.fiit.stuba.sk/pis/students/team024pouzivatel/types", IsWrapped=true)]
    public partial class getByAttributeValueRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024pouzivatel/types", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string attribute_name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024pouzivatel/types", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string attribute_value;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024pouzivatel/types", Order=2)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("id", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Nullable<int>[] ids;
        
        public getByAttributeValueRequest() {
        }
        
        public getByAttributeValueRequest(string attribute_name, string attribute_value, System.Nullable<int>[] ids) {
            this.attribute_name = attribute_name;
            this.attribute_value = attribute_value;
            this.ids = ids;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getByAttributeValueResponse", WrapperNamespace="http://labss2.fiit.stuba.sk/pis/students/team024pouzivatel/types", IsWrapped=true)]
    public partial class getByAttributeValueResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024pouzivatel/types", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("pouzivatel", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WebApi.PouzivatelWsdlService.Pouzivatels[] pouzivatels;
        
        public getByAttributeValueResponse() {
        }
        
        public getByAttributeValueResponse(WebApi.PouzivatelWsdlService.Pouzivatels[] pouzivatels) {
            this.pouzivatels = pouzivatels;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getByNumericCondition", WrapperNamespace="http://labss2.fiit.stuba.sk/pis/students/team024pouzivatel/types", IsWrapped=true)]
    public partial class getByNumericConditionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024pouzivatel/types", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string attribute_name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024pouzivatel/types", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string attribute_value;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024pouzivatel/types", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string math_condition;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024pouzivatel/types", Order=3)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("id", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Nullable<int>[] ids;
        
        public getByNumericConditionRequest() {
        }
        
        public getByNumericConditionRequest(string attribute_name, string attribute_value, string math_condition, System.Nullable<int>[] ids) {
            this.attribute_name = attribute_name;
            this.attribute_value = attribute_value;
            this.math_condition = math_condition;
            this.ids = ids;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getByNumericConditionResponse", WrapperNamespace="http://labss2.fiit.stuba.sk/pis/students/team024pouzivatel/types", IsWrapped=true)]
    public partial class getByNumericConditionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024pouzivatel/types", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("pouzivatel", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WebApi.PouzivatelWsdlService.Pouzivatels[] pouzivatels;
        
        public getByNumericConditionResponse() {
        }
        
        public getByNumericConditionResponse(WebApi.PouzivatelWsdlService.Pouzivatels[] pouzivatels) {
            this.pouzivatels = pouzivatels;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAll", WrapperNamespace="http://labss2.fiit.stuba.sk/pis/students/team024pouzivatel/types", IsWrapped=true)]
    public partial class getAllRequest {
        
        public getAllRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllResponse", WrapperNamespace="http://labss2.fiit.stuba.sk/pis/students/team024pouzivatel/types", IsWrapped=true)]
    public partial class getAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024pouzivatel/types", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("pouzivatel", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WebApi.PouzivatelWsdlService.Pouzivatels[] pouzivatels;
        
        public getAllResponse() {
        }
        
        public getAllResponse(WebApi.PouzivatelWsdlService.Pouzivatels[] pouzivatels) {
            this.pouzivatels = pouzivatels;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insert", WrapperNamespace="http://labss2.fiit.stuba.sk/pis/students/team024pouzivatel/types", IsWrapped=true)]
    public partial class insertRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024pouzivatel/types", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string team_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024pouzivatel/types", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string team_password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024pouzivatel/types", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WebApi.PouzivatelWsdlService.Pouzivatel Pouzivatel;
        
        public insertRequest() {
        }
        
        public insertRequest(string team_id, string team_password, WebApi.PouzivatelWsdlService.Pouzivatel Pouzivatel) {
            this.team_id = team_id;
            this.team_password = team_password;
            this.Pouzivatel = Pouzivatel;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertResponse", WrapperNamespace="http://labss2.fiit.stuba.sk/pis/students/team024pouzivatel/types", IsWrapped=true)]
    public partial class insertResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024pouzivatel/types", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public insertResponse() {
        }
        
        public insertResponse(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="update", WrapperNamespace="http://labss2.fiit.stuba.sk/pis/students/team024pouzivatel/types", IsWrapped=true)]
    public partial class updateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024pouzivatel/types", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string team_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024pouzivatel/types", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string team_password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024pouzivatel/types", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int entity_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024pouzivatel/types", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WebApi.PouzivatelWsdlService.Pouzivatel Pouzivatel;
        
        public updateRequest() {
        }
        
        public updateRequest(string team_id, string team_password, int entity_id, WebApi.PouzivatelWsdlService.Pouzivatel Pouzivatel) {
            this.team_id = team_id;
            this.team_password = team_password;
            this.entity_id = entity_id;
            this.Pouzivatel = Pouzivatel;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateResponse", WrapperNamespace="http://labss2.fiit.stuba.sk/pis/students/team024pouzivatel/types", IsWrapped=true)]
    public partial class updateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024pouzivatel/types", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int updates;
        
        public updateResponse() {
        }
        
        public updateResponse(int updates) {
            this.updates = updates;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="delete", WrapperNamespace="http://labss2.fiit.stuba.sk/pis/students/team024pouzivatel/types", IsWrapped=true)]
    public partial class deleteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024pouzivatel/types", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string team_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024pouzivatel/types", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string team_password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024pouzivatel/types", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int entity_id;
        
        public deleteRequest() {
        }
        
        public deleteRequest(string team_id, string team_password, int entity_id) {
            this.team_id = team_id;
            this.team_password = team_password;
            this.entity_id = entity_id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteResponse", WrapperNamespace="http://labss2.fiit.stuba.sk/pis/students/team024pouzivatel/types", IsWrapped=true)]
    public partial class deleteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024pouzivatel/types", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool deleted;
        
        public deleteResponse() {
        }
        
        public deleteResponse(bool deleted) {
            this.deleted = deleted;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Team024PouzivatelPortTypeChannel : WebApi.PouzivatelWsdlService.Team024PouzivatelPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Team024PouzivatelPortTypeClient : System.ServiceModel.ClientBase<WebApi.PouzivatelWsdlService.Team024PouzivatelPortType>, WebApi.PouzivatelWsdlService.Team024PouzivatelPortType {
        
        public Team024PouzivatelPortTypeClient() {
        }
        
        public Team024PouzivatelPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Team024PouzivatelPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Team024PouzivatelPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Team024PouzivatelPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApi.PouzivatelWsdlService.getByIdResponse WebApi.PouzivatelWsdlService.Team024PouzivatelPortType.getById(WebApi.PouzivatelWsdlService.getByIdRequest request) {
            return base.Channel.getById(request);
        }
        
        public WebApi.PouzivatelWsdlService.Pouzivatel getById(int id) {
            WebApi.PouzivatelWsdlService.getByIdRequest inValue = new WebApi.PouzivatelWsdlService.getByIdRequest();
            inValue.id = id;
            WebApi.PouzivatelWsdlService.getByIdResponse retVal = ((WebApi.PouzivatelWsdlService.Team024PouzivatelPortType)(this)).getById(inValue);
            return retVal.pouzivatel;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApi.PouzivatelWsdlService.getByIdResponse> WebApi.PouzivatelWsdlService.Team024PouzivatelPortType.getByIdAsync(WebApi.PouzivatelWsdlService.getByIdRequest request) {
            return base.Channel.getByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApi.PouzivatelWsdlService.getByIdResponse> getByIdAsync(int id) {
            WebApi.PouzivatelWsdlService.getByIdRequest inValue = new WebApi.PouzivatelWsdlService.getByIdRequest();
            inValue.id = id;
            return ((WebApi.PouzivatelWsdlService.Team024PouzivatelPortType)(this)).getByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApi.PouzivatelWsdlService.getByAttributeValueResponse WebApi.PouzivatelWsdlService.Team024PouzivatelPortType.getByAttributeValue(WebApi.PouzivatelWsdlService.getByAttributeValueRequest request) {
            return base.Channel.getByAttributeValue(request);
        }
        
        public WebApi.PouzivatelWsdlService.Pouzivatels[] getByAttributeValue(string attribute_name, string attribute_value, System.Nullable<int>[] ids) {
            WebApi.PouzivatelWsdlService.getByAttributeValueRequest inValue = new WebApi.PouzivatelWsdlService.getByAttributeValueRequest();
            inValue.attribute_name = attribute_name;
            inValue.attribute_value = attribute_value;
            inValue.ids = ids;
            WebApi.PouzivatelWsdlService.getByAttributeValueResponse retVal = ((WebApi.PouzivatelWsdlService.Team024PouzivatelPortType)(this)).getByAttributeValue(inValue);
            return retVal.pouzivatels;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApi.PouzivatelWsdlService.getByAttributeValueResponse> WebApi.PouzivatelWsdlService.Team024PouzivatelPortType.getByAttributeValueAsync(WebApi.PouzivatelWsdlService.getByAttributeValueRequest request) {
            return base.Channel.getByAttributeValueAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApi.PouzivatelWsdlService.getByAttributeValueResponse> getByAttributeValueAsync(string attribute_name, string attribute_value, System.Nullable<int>[] ids) {
            WebApi.PouzivatelWsdlService.getByAttributeValueRequest inValue = new WebApi.PouzivatelWsdlService.getByAttributeValueRequest();
            inValue.attribute_name = attribute_name;
            inValue.attribute_value = attribute_value;
            inValue.ids = ids;
            return ((WebApi.PouzivatelWsdlService.Team024PouzivatelPortType)(this)).getByAttributeValueAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApi.PouzivatelWsdlService.getByNumericConditionResponse WebApi.PouzivatelWsdlService.Team024PouzivatelPortType.getByNumericCondition(WebApi.PouzivatelWsdlService.getByNumericConditionRequest request) {
            return base.Channel.getByNumericCondition(request);
        }
        
        public WebApi.PouzivatelWsdlService.Pouzivatels[] getByNumericCondition(string attribute_name, string attribute_value, string math_condition, System.Nullable<int>[] ids) {
            WebApi.PouzivatelWsdlService.getByNumericConditionRequest inValue = new WebApi.PouzivatelWsdlService.getByNumericConditionRequest();
            inValue.attribute_name = attribute_name;
            inValue.attribute_value = attribute_value;
            inValue.math_condition = math_condition;
            inValue.ids = ids;
            WebApi.PouzivatelWsdlService.getByNumericConditionResponse retVal = ((WebApi.PouzivatelWsdlService.Team024PouzivatelPortType)(this)).getByNumericCondition(inValue);
            return retVal.pouzivatels;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApi.PouzivatelWsdlService.getByNumericConditionResponse> WebApi.PouzivatelWsdlService.Team024PouzivatelPortType.getByNumericConditionAsync(WebApi.PouzivatelWsdlService.getByNumericConditionRequest request) {
            return base.Channel.getByNumericConditionAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApi.PouzivatelWsdlService.getByNumericConditionResponse> getByNumericConditionAsync(string attribute_name, string attribute_value, string math_condition, System.Nullable<int>[] ids) {
            WebApi.PouzivatelWsdlService.getByNumericConditionRequest inValue = new WebApi.PouzivatelWsdlService.getByNumericConditionRequest();
            inValue.attribute_name = attribute_name;
            inValue.attribute_value = attribute_value;
            inValue.math_condition = math_condition;
            inValue.ids = ids;
            return ((WebApi.PouzivatelWsdlService.Team024PouzivatelPortType)(this)).getByNumericConditionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApi.PouzivatelWsdlService.getAllResponse WebApi.PouzivatelWsdlService.Team024PouzivatelPortType.getAll(WebApi.PouzivatelWsdlService.getAllRequest request) {
            return base.Channel.getAll(request);
        }
        
        public WebApi.PouzivatelWsdlService.Pouzivatels[] getAll() {
            WebApi.PouzivatelWsdlService.getAllRequest inValue = new WebApi.PouzivatelWsdlService.getAllRequest();
            WebApi.PouzivatelWsdlService.getAllResponse retVal = ((WebApi.PouzivatelWsdlService.Team024PouzivatelPortType)(this)).getAll(inValue);
            return retVal.pouzivatels;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApi.PouzivatelWsdlService.getAllResponse> WebApi.PouzivatelWsdlService.Team024PouzivatelPortType.getAllAsync(WebApi.PouzivatelWsdlService.getAllRequest request) {
            return base.Channel.getAllAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApi.PouzivatelWsdlService.getAllResponse> getAllAsync() {
            WebApi.PouzivatelWsdlService.getAllRequest inValue = new WebApi.PouzivatelWsdlService.getAllRequest();
            return ((WebApi.PouzivatelWsdlService.Team024PouzivatelPortType)(this)).getAllAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApi.PouzivatelWsdlService.insertResponse WebApi.PouzivatelWsdlService.Team024PouzivatelPortType.insert(WebApi.PouzivatelWsdlService.insertRequest request) {
            return base.Channel.insert(request);
        }
        
        public int insert(string team_id, string team_password, WebApi.PouzivatelWsdlService.Pouzivatel Pouzivatel) {
            WebApi.PouzivatelWsdlService.insertRequest inValue = new WebApi.PouzivatelWsdlService.insertRequest();
            inValue.team_id = team_id;
            inValue.team_password = team_password;
            inValue.Pouzivatel = Pouzivatel;
            WebApi.PouzivatelWsdlService.insertResponse retVal = ((WebApi.PouzivatelWsdlService.Team024PouzivatelPortType)(this)).insert(inValue);
            return retVal.id;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApi.PouzivatelWsdlService.insertResponse> WebApi.PouzivatelWsdlService.Team024PouzivatelPortType.insertAsync(WebApi.PouzivatelWsdlService.insertRequest request) {
            return base.Channel.insertAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApi.PouzivatelWsdlService.insertResponse> insertAsync(string team_id, string team_password, WebApi.PouzivatelWsdlService.Pouzivatel Pouzivatel) {
            WebApi.PouzivatelWsdlService.insertRequest inValue = new WebApi.PouzivatelWsdlService.insertRequest();
            inValue.team_id = team_id;
            inValue.team_password = team_password;
            inValue.Pouzivatel = Pouzivatel;
            return ((WebApi.PouzivatelWsdlService.Team024PouzivatelPortType)(this)).insertAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApi.PouzivatelWsdlService.updateResponse WebApi.PouzivatelWsdlService.Team024PouzivatelPortType.update(WebApi.PouzivatelWsdlService.updateRequest request) {
            return base.Channel.update(request);
        }
        
        public int update(string team_id, string team_password, int entity_id, WebApi.PouzivatelWsdlService.Pouzivatel Pouzivatel) {
            WebApi.PouzivatelWsdlService.updateRequest inValue = new WebApi.PouzivatelWsdlService.updateRequest();
            inValue.team_id = team_id;
            inValue.team_password = team_password;
            inValue.entity_id = entity_id;
            inValue.Pouzivatel = Pouzivatel;
            WebApi.PouzivatelWsdlService.updateResponse retVal = ((WebApi.PouzivatelWsdlService.Team024PouzivatelPortType)(this)).update(inValue);
            return retVal.updates;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApi.PouzivatelWsdlService.updateResponse> WebApi.PouzivatelWsdlService.Team024PouzivatelPortType.updateAsync(WebApi.PouzivatelWsdlService.updateRequest request) {
            return base.Channel.updateAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApi.PouzivatelWsdlService.updateResponse> updateAsync(string team_id, string team_password, int entity_id, WebApi.PouzivatelWsdlService.Pouzivatel Pouzivatel) {
            WebApi.PouzivatelWsdlService.updateRequest inValue = new WebApi.PouzivatelWsdlService.updateRequest();
            inValue.team_id = team_id;
            inValue.team_password = team_password;
            inValue.entity_id = entity_id;
            inValue.Pouzivatel = Pouzivatel;
            return ((WebApi.PouzivatelWsdlService.Team024PouzivatelPortType)(this)).updateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApi.PouzivatelWsdlService.deleteResponse WebApi.PouzivatelWsdlService.Team024PouzivatelPortType.delete(WebApi.PouzivatelWsdlService.deleteRequest request) {
            return base.Channel.delete(request);
        }
        
        public bool delete(string team_id, string team_password, int entity_id) {
            WebApi.PouzivatelWsdlService.deleteRequest inValue = new WebApi.PouzivatelWsdlService.deleteRequest();
            inValue.team_id = team_id;
            inValue.team_password = team_password;
            inValue.entity_id = entity_id;
            WebApi.PouzivatelWsdlService.deleteResponse retVal = ((WebApi.PouzivatelWsdlService.Team024PouzivatelPortType)(this)).delete(inValue);
            return retVal.deleted;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApi.PouzivatelWsdlService.deleteResponse> WebApi.PouzivatelWsdlService.Team024PouzivatelPortType.deleteAsync(WebApi.PouzivatelWsdlService.deleteRequest request) {
            return base.Channel.deleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApi.PouzivatelWsdlService.deleteResponse> deleteAsync(string team_id, string team_password, int entity_id) {
            WebApi.PouzivatelWsdlService.deleteRequest inValue = new WebApi.PouzivatelWsdlService.deleteRequest();
            inValue.team_id = team_id;
            inValue.team_password = team_password;
            inValue.entity_id = entity_id;
            return ((WebApi.PouzivatelWsdlService.Team024PouzivatelPortType)(this)).deleteAsync(inValue);
        }
    }
}
