//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.BookWsdlService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024kniha", ConfigurationName="BookWsdlService.Team024KnihaPortType")]
    public interface Team024KnihaPortType {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://labss2.fiit.stuba.sk/pis/students/team024kniha/types) of message getByIdRequest does not match the default value (http://labss2.fiit.stuba.sk/pis/students/team024kniha)
        [System.ServiceModel.OperationContractAttribute(Action="http://labss2.fiit.stuba.sk/pis/students/team024kniha/#getById", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebApi.BookWsdlService.getByIdResponse getById(WebApi.BookWsdlService.getByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://labss2.fiit.stuba.sk/pis/students/team024kniha/#getById", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApi.BookWsdlService.getByIdResponse> getByIdAsync(WebApi.BookWsdlService.getByIdRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://labss2.fiit.stuba.sk/pis/students/team024kniha/types) of message getByAttributeValueRequest does not match the default value (http://labss2.fiit.stuba.sk/pis/students/team024kniha)
        [System.ServiceModel.OperationContractAttribute(Action="http://labss2.fiit.stuba.sk/pis/students/team024kniha/#getByAttributeValue", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebApi.BookWsdlService.getByAttributeValueResponse getByAttributeValue(WebApi.BookWsdlService.getByAttributeValueRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://labss2.fiit.stuba.sk/pis/students/team024kniha/#getByAttributeValue", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApi.BookWsdlService.getByAttributeValueResponse> getByAttributeValueAsync(WebApi.BookWsdlService.getByAttributeValueRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://labss2.fiit.stuba.sk/pis/students/team024kniha/types) of message getByNumericConditionRequest does not match the default value (http://labss2.fiit.stuba.sk/pis/students/team024kniha)
        [System.ServiceModel.OperationContractAttribute(Action="http://labss2.fiit.stuba.sk/pis/students/team024kniha/#getByNumericCondition", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebApi.BookWsdlService.getByNumericConditionResponse getByNumericCondition(WebApi.BookWsdlService.getByNumericConditionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://labss2.fiit.stuba.sk/pis/students/team024kniha/#getByNumericCondition", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApi.BookWsdlService.getByNumericConditionResponse> getByNumericConditionAsync(WebApi.BookWsdlService.getByNumericConditionRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://labss2.fiit.stuba.sk/pis/students/team024kniha/types) of message getAllRequest does not match the default value (http://labss2.fiit.stuba.sk/pis/students/team024kniha)
        [System.ServiceModel.OperationContractAttribute(Action="http://labss2.fiit.stuba.sk/pis/students/team024kniha/#getAll", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebApi.BookWsdlService.getAllResponse getAll(WebApi.BookWsdlService.getAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://labss2.fiit.stuba.sk/pis/students/team024kniha/#getAll", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApi.BookWsdlService.getAllResponse> getAllAsync(WebApi.BookWsdlService.getAllRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://labss2.fiit.stuba.sk/pis/students/team024kniha/types) of message insertRequest does not match the default value (http://labss2.fiit.stuba.sk/pis/students/team024kniha)
        [System.ServiceModel.OperationContractAttribute(Action="http://labss2.fiit.stuba.sk/pis/students/team024kniha/#insert", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebApi.BookWsdlService.insertResponse insert(WebApi.BookWsdlService.insertRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://labss2.fiit.stuba.sk/pis/students/team024kniha/#insert", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApi.BookWsdlService.insertResponse> insertAsync(WebApi.BookWsdlService.insertRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://labss2.fiit.stuba.sk/pis/students/team024kniha/types) of message updateRequest does not match the default value (http://labss2.fiit.stuba.sk/pis/students/team024kniha)
        [System.ServiceModel.OperationContractAttribute(Action="http://labss2.fiit.stuba.sk/pis/students/team024kniha/#update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebApi.BookWsdlService.updateResponse update(WebApi.BookWsdlService.updateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://labss2.fiit.stuba.sk/pis/students/team024kniha/#update", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApi.BookWsdlService.updateResponse> updateAsync(WebApi.BookWsdlService.updateRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://labss2.fiit.stuba.sk/pis/students/team024kniha/types) of message deleteRequest does not match the default value (http://labss2.fiit.stuba.sk/pis/students/team024kniha)
        [System.ServiceModel.OperationContractAttribute(Action="http://labss2.fiit.stuba.sk/pis/students/team024kniha/#delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebApi.BookWsdlService.deleteResponse delete(WebApi.BookWsdlService.deleteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://labss2.fiit.stuba.sk/pis/students/team024kniha/#delete", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApi.BookWsdlService.deleteResponse> deleteAsync(WebApi.BookWsdlService.deleteRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024kniha/types")]
    public partial class Kniha : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string nameField;
        
        private string iSBNField;
        
        private string autorField;
        
        private string zanerField;
        
        private string popisField;
        
        private System.DateTime rokVydaniaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ISBN {
            get {
                return this.iSBNField;
            }
            set {
                this.iSBNField = value;
                this.RaisePropertyChanged("ISBN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string autor {
            get {
                return this.autorField;
            }
            set {
                this.autorField = value;
                this.RaisePropertyChanged("autor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string zaner {
            get {
                return this.zanerField;
            }
            set {
                this.zanerField = value;
                this.RaisePropertyChanged("zaner");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string popis {
            get {
                return this.popisField;
            }
            set {
                this.popisField = value;
                this.RaisePropertyChanged("popis");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=6)]
        public System.DateTime rokVydania {
            get {
                return this.rokVydaniaField;
            }
            set {
                this.rokVydaniaField = value;
                this.RaisePropertyChanged("rokVydania");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024kniha/types")]
    public partial class Knihas : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string nameField;
        
        private string iSBNField;
        
        private string autorField;
        
        private string zanerField;
        
        private string popisField;
        
        private System.DateTime rokVydaniaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ISBN {
            get {
                return this.iSBNField;
            }
            set {
                this.iSBNField = value;
                this.RaisePropertyChanged("ISBN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string autor {
            get {
                return this.autorField;
            }
            set {
                this.autorField = value;
                this.RaisePropertyChanged("autor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string zaner {
            get {
                return this.zanerField;
            }
            set {
                this.zanerField = value;
                this.RaisePropertyChanged("zaner");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string popis {
            get {
                return this.popisField;
            }
            set {
                this.popisField = value;
                this.RaisePropertyChanged("popis");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=6)]
        public System.DateTime rokVydania {
            get {
                return this.rokVydaniaField;
            }
            set {
                this.rokVydaniaField = value;
                this.RaisePropertyChanged("rokVydania");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getById", WrapperNamespace="http://labss2.fiit.stuba.sk/pis/students/team024kniha/types", IsWrapped=true)]
    public partial class getByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024kniha/types", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public getByIdRequest() {
        }
        
        public getByIdRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getByIdResponse", WrapperNamespace="http://labss2.fiit.stuba.sk/pis/students/team024kniha/types", IsWrapped=true)]
    public partial class getByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024kniha/types", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WebApi.BookWsdlService.Kniha kniha;
        
        public getByIdResponse() {
        }
        
        public getByIdResponse(WebApi.BookWsdlService.Kniha kniha) {
            this.kniha = kniha;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getByAttributeValue", WrapperNamespace="http://labss2.fiit.stuba.sk/pis/students/team024kniha/types", IsWrapped=true)]
    public partial class getByAttributeValueRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024kniha/types", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string attribute_name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024kniha/types", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string attribute_value;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024kniha/types", Order=2)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("id", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Nullable<int>[] ids;
        
        public getByAttributeValueRequest() {
        }
        
        public getByAttributeValueRequest(string attribute_name, string attribute_value, System.Nullable<int>[] ids) {
            this.attribute_name = attribute_name;
            this.attribute_value = attribute_value;
            this.ids = ids;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getByAttributeValueResponse", WrapperNamespace="http://labss2.fiit.stuba.sk/pis/students/team024kniha/types", IsWrapped=true)]
    public partial class getByAttributeValueResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024kniha/types", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("kniha", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WebApi.BookWsdlService.Knihas[] knihas;
        
        public getByAttributeValueResponse() {
        }
        
        public getByAttributeValueResponse(WebApi.BookWsdlService.Knihas[] knihas) {
            this.knihas = knihas;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getByNumericCondition", WrapperNamespace="http://labss2.fiit.stuba.sk/pis/students/team024kniha/types", IsWrapped=true)]
    public partial class getByNumericConditionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024kniha/types", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string attribute_name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024kniha/types", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string attribute_value;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024kniha/types", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string math_condition;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024kniha/types", Order=3)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("id", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Nullable<int>[] ids;
        
        public getByNumericConditionRequest() {
        }
        
        public getByNumericConditionRequest(string attribute_name, string attribute_value, string math_condition, System.Nullable<int>[] ids) {
            this.attribute_name = attribute_name;
            this.attribute_value = attribute_value;
            this.math_condition = math_condition;
            this.ids = ids;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getByNumericConditionResponse", WrapperNamespace="http://labss2.fiit.stuba.sk/pis/students/team024kniha/types", IsWrapped=true)]
    public partial class getByNumericConditionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024kniha/types", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("kniha", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WebApi.BookWsdlService.Knihas[] knihas;
        
        public getByNumericConditionResponse() {
        }
        
        public getByNumericConditionResponse(WebApi.BookWsdlService.Knihas[] knihas) {
            this.knihas = knihas;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAll", WrapperNamespace="http://labss2.fiit.stuba.sk/pis/students/team024kniha/types", IsWrapped=true)]
    public partial class getAllRequest {
        
        public getAllRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllResponse", WrapperNamespace="http://labss2.fiit.stuba.sk/pis/students/team024kniha/types", IsWrapped=true)]
    public partial class getAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024kniha/types", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("kniha", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WebApi.BookWsdlService.Knihas[] knihas;
        
        public getAllResponse() {
        }
        
        public getAllResponse(WebApi.BookWsdlService.Knihas[] knihas) {
            this.knihas = knihas;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insert", WrapperNamespace="http://labss2.fiit.stuba.sk/pis/students/team024kniha/types", IsWrapped=true)]
    public partial class insertRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024kniha/types", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string team_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024kniha/types", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string team_password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024kniha/types", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WebApi.BookWsdlService.Kniha Kniha;
        
        public insertRequest() {
        }
        
        public insertRequest(string team_id, string team_password, WebApi.BookWsdlService.Kniha Kniha) {
            this.team_id = team_id;
            this.team_password = team_password;
            this.Kniha = Kniha;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertResponse", WrapperNamespace="http://labss2.fiit.stuba.sk/pis/students/team024kniha/types", IsWrapped=true)]
    public partial class insertResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024kniha/types", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public insertResponse() {
        }
        
        public insertResponse(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="update", WrapperNamespace="http://labss2.fiit.stuba.sk/pis/students/team024kniha/types", IsWrapped=true)]
    public partial class updateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024kniha/types", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string team_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024kniha/types", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string team_password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024kniha/types", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int entity_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024kniha/types", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WebApi.BookWsdlService.Kniha Kniha;
        
        public updateRequest() {
        }
        
        public updateRequest(string team_id, string team_password, int entity_id, WebApi.BookWsdlService.Kniha Kniha) {
            this.team_id = team_id;
            this.team_password = team_password;
            this.entity_id = entity_id;
            this.Kniha = Kniha;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateResponse", WrapperNamespace="http://labss2.fiit.stuba.sk/pis/students/team024kniha/types", IsWrapped=true)]
    public partial class updateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024kniha/types", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int updates;
        
        public updateResponse() {
        }
        
        public updateResponse(int updates) {
            this.updates = updates;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="delete", WrapperNamespace="http://labss2.fiit.stuba.sk/pis/students/team024kniha/types", IsWrapped=true)]
    public partial class deleteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024kniha/types", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string team_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024kniha/types", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string team_password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024kniha/types", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int entity_id;
        
        public deleteRequest() {
        }
        
        public deleteRequest(string team_id, string team_password, int entity_id) {
            this.team_id = team_id;
            this.team_password = team_password;
            this.entity_id = entity_id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteResponse", WrapperNamespace="http://labss2.fiit.stuba.sk/pis/students/team024kniha/types", IsWrapped=true)]
    public partial class deleteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://labss2.fiit.stuba.sk/pis/students/team024kniha/types", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool deleted;
        
        public deleteResponse() {
        }
        
        public deleteResponse(bool deleted) {
            this.deleted = deleted;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Team024KnihaPortTypeChannel : WebApi.BookWsdlService.Team024KnihaPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Team024KnihaPortTypeClient : System.ServiceModel.ClientBase<WebApi.BookWsdlService.Team024KnihaPortType>, WebApi.BookWsdlService.Team024KnihaPortType {
        
        public Team024KnihaPortTypeClient() {
        }
        
        public Team024KnihaPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Team024KnihaPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Team024KnihaPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Team024KnihaPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApi.BookWsdlService.getByIdResponse WebApi.BookWsdlService.Team024KnihaPortType.getById(WebApi.BookWsdlService.getByIdRequest request) {
            return base.Channel.getById(request);
        }
        
        public WebApi.BookWsdlService.Kniha getById(int id) {
            WebApi.BookWsdlService.getByIdRequest inValue = new WebApi.BookWsdlService.getByIdRequest();
            inValue.id = id;
            WebApi.BookWsdlService.getByIdResponse retVal = ((WebApi.BookWsdlService.Team024KnihaPortType)(this)).getById(inValue);
            return retVal.kniha;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApi.BookWsdlService.getByIdResponse> WebApi.BookWsdlService.Team024KnihaPortType.getByIdAsync(WebApi.BookWsdlService.getByIdRequest request) {
            return base.Channel.getByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApi.BookWsdlService.getByIdResponse> getByIdAsync(int id) {
            WebApi.BookWsdlService.getByIdRequest inValue = new WebApi.BookWsdlService.getByIdRequest();
            inValue.id = id;
            return ((WebApi.BookWsdlService.Team024KnihaPortType)(this)).getByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApi.BookWsdlService.getByAttributeValueResponse WebApi.BookWsdlService.Team024KnihaPortType.getByAttributeValue(WebApi.BookWsdlService.getByAttributeValueRequest request) {
            return base.Channel.getByAttributeValue(request);
        }
        
        public WebApi.BookWsdlService.Knihas[] getByAttributeValue(string attribute_name, string attribute_value, System.Nullable<int>[] ids) {
            WebApi.BookWsdlService.getByAttributeValueRequest inValue = new WebApi.BookWsdlService.getByAttributeValueRequest();
            inValue.attribute_name = attribute_name;
            inValue.attribute_value = attribute_value;
            inValue.ids = ids;
            WebApi.BookWsdlService.getByAttributeValueResponse retVal = ((WebApi.BookWsdlService.Team024KnihaPortType)(this)).getByAttributeValue(inValue);
            return retVal.knihas;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApi.BookWsdlService.getByAttributeValueResponse> WebApi.BookWsdlService.Team024KnihaPortType.getByAttributeValueAsync(WebApi.BookWsdlService.getByAttributeValueRequest request) {
            return base.Channel.getByAttributeValueAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApi.BookWsdlService.getByAttributeValueResponse> getByAttributeValueAsync(string attribute_name, string attribute_value, System.Nullable<int>[] ids) {
            WebApi.BookWsdlService.getByAttributeValueRequest inValue = new WebApi.BookWsdlService.getByAttributeValueRequest();
            inValue.attribute_name = attribute_name;
            inValue.attribute_value = attribute_value;
            inValue.ids = ids;
            return ((WebApi.BookWsdlService.Team024KnihaPortType)(this)).getByAttributeValueAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApi.BookWsdlService.getByNumericConditionResponse WebApi.BookWsdlService.Team024KnihaPortType.getByNumericCondition(WebApi.BookWsdlService.getByNumericConditionRequest request) {
            return base.Channel.getByNumericCondition(request);
        }
        
        public WebApi.BookWsdlService.Knihas[] getByNumericCondition(string attribute_name, string attribute_value, string math_condition, System.Nullable<int>[] ids) {
            WebApi.BookWsdlService.getByNumericConditionRequest inValue = new WebApi.BookWsdlService.getByNumericConditionRequest();
            inValue.attribute_name = attribute_name;
            inValue.attribute_value = attribute_value;
            inValue.math_condition = math_condition;
            inValue.ids = ids;
            WebApi.BookWsdlService.getByNumericConditionResponse retVal = ((WebApi.BookWsdlService.Team024KnihaPortType)(this)).getByNumericCondition(inValue);
            return retVal.knihas;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApi.BookWsdlService.getByNumericConditionResponse> WebApi.BookWsdlService.Team024KnihaPortType.getByNumericConditionAsync(WebApi.BookWsdlService.getByNumericConditionRequest request) {
            return base.Channel.getByNumericConditionAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApi.BookWsdlService.getByNumericConditionResponse> getByNumericConditionAsync(string attribute_name, string attribute_value, string math_condition, System.Nullable<int>[] ids) {
            WebApi.BookWsdlService.getByNumericConditionRequest inValue = new WebApi.BookWsdlService.getByNumericConditionRequest();
            inValue.attribute_name = attribute_name;
            inValue.attribute_value = attribute_value;
            inValue.math_condition = math_condition;
            inValue.ids = ids;
            return ((WebApi.BookWsdlService.Team024KnihaPortType)(this)).getByNumericConditionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApi.BookWsdlService.getAllResponse WebApi.BookWsdlService.Team024KnihaPortType.getAll(WebApi.BookWsdlService.getAllRequest request) {
            return base.Channel.getAll(request);
        }
        
        public WebApi.BookWsdlService.Knihas[] getAll() {
            WebApi.BookWsdlService.getAllRequest inValue = new WebApi.BookWsdlService.getAllRequest();
            WebApi.BookWsdlService.getAllResponse retVal = ((WebApi.BookWsdlService.Team024KnihaPortType)(this)).getAll(inValue);
            return retVal.knihas;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApi.BookWsdlService.getAllResponse> WebApi.BookWsdlService.Team024KnihaPortType.getAllAsync(WebApi.BookWsdlService.getAllRequest request) {
            return base.Channel.getAllAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApi.BookWsdlService.getAllResponse> getAllAsync() {
            WebApi.BookWsdlService.getAllRequest inValue = new WebApi.BookWsdlService.getAllRequest();
            return ((WebApi.BookWsdlService.Team024KnihaPortType)(this)).getAllAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApi.BookWsdlService.insertResponse WebApi.BookWsdlService.Team024KnihaPortType.insert(WebApi.BookWsdlService.insertRequest request) {
            return base.Channel.insert(request);
        }
        
        public int insert(string team_id, string team_password, WebApi.BookWsdlService.Kniha Kniha) {
            WebApi.BookWsdlService.insertRequest inValue = new WebApi.BookWsdlService.insertRequest();
            inValue.team_id = team_id;
            inValue.team_password = team_password;
            inValue.Kniha = Kniha;
            WebApi.BookWsdlService.insertResponse retVal = ((WebApi.BookWsdlService.Team024KnihaPortType)(this)).insert(inValue);
            return retVal.id;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApi.BookWsdlService.insertResponse> WebApi.BookWsdlService.Team024KnihaPortType.insertAsync(WebApi.BookWsdlService.insertRequest request) {
            return base.Channel.insertAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApi.BookWsdlService.insertResponse> insertAsync(string team_id, string team_password, WebApi.BookWsdlService.Kniha Kniha) {
            WebApi.BookWsdlService.insertRequest inValue = new WebApi.BookWsdlService.insertRequest();
            inValue.team_id = team_id;
            inValue.team_password = team_password;
            inValue.Kniha = Kniha;
            return ((WebApi.BookWsdlService.Team024KnihaPortType)(this)).insertAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApi.BookWsdlService.updateResponse WebApi.BookWsdlService.Team024KnihaPortType.update(WebApi.BookWsdlService.updateRequest request) {
            return base.Channel.update(request);
        }
        
        public int update(string team_id, string team_password, int entity_id, WebApi.BookWsdlService.Kniha Kniha) {
            WebApi.BookWsdlService.updateRequest inValue = new WebApi.BookWsdlService.updateRequest();
            inValue.team_id = team_id;
            inValue.team_password = team_password;
            inValue.entity_id = entity_id;
            inValue.Kniha = Kniha;
            WebApi.BookWsdlService.updateResponse retVal = ((WebApi.BookWsdlService.Team024KnihaPortType)(this)).update(inValue);
            return retVal.updates;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApi.BookWsdlService.updateResponse> WebApi.BookWsdlService.Team024KnihaPortType.updateAsync(WebApi.BookWsdlService.updateRequest request) {
            return base.Channel.updateAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApi.BookWsdlService.updateResponse> updateAsync(string team_id, string team_password, int entity_id, WebApi.BookWsdlService.Kniha Kniha) {
            WebApi.BookWsdlService.updateRequest inValue = new WebApi.BookWsdlService.updateRequest();
            inValue.team_id = team_id;
            inValue.team_password = team_password;
            inValue.entity_id = entity_id;
            inValue.Kniha = Kniha;
            return ((WebApi.BookWsdlService.Team024KnihaPortType)(this)).updateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApi.BookWsdlService.deleteResponse WebApi.BookWsdlService.Team024KnihaPortType.delete(WebApi.BookWsdlService.deleteRequest request) {
            return base.Channel.delete(request);
        }
        
        public bool delete(string team_id, string team_password, int entity_id) {
            WebApi.BookWsdlService.deleteRequest inValue = new WebApi.BookWsdlService.deleteRequest();
            inValue.team_id = team_id;
            inValue.team_password = team_password;
            inValue.entity_id = entity_id;
            WebApi.BookWsdlService.deleteResponse retVal = ((WebApi.BookWsdlService.Team024KnihaPortType)(this)).delete(inValue);
            return retVal.deleted;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApi.BookWsdlService.deleteResponse> WebApi.BookWsdlService.Team024KnihaPortType.deleteAsync(WebApi.BookWsdlService.deleteRequest request) {
            return base.Channel.deleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApi.BookWsdlService.deleteResponse> deleteAsync(string team_id, string team_password, int entity_id) {
            WebApi.BookWsdlService.deleteRequest inValue = new WebApi.BookWsdlService.deleteRequest();
            inValue.team_id = team_id;
            inValue.team_password = team_password;
            inValue.entity_id = entity_id;
            return ((WebApi.BookWsdlService.Team024KnihaPortType)(this)).deleteAsync(inValue);
        }
    }
}
